markets = ["binance_spot"]
db_path = "/home/syple/code/rdata/data.db"

[binance_spot]
cache_capacity = 100
market_refresh_interval_secs = 30
trade_refresh_interval_secs = 5
api_base_url = "https://api.binance.com"
stream_base_url = "wss://stream.binance.com:9443/stream"
stream_api_base_url = "wss://ws-api.testnet.binance.vision/ws-api/v3"
api_key = "GMh8WTFiTiRPpbt1EFwYaDEunKN9gJy9qgRyYF8irvSYCdgjYcIaACDeyfKFOMcq"
secret_key = "NgIxnbabjf6cTnPYZpyVDAP7UoVNm3wzhJcLh89FYWSA5SkXJlCZD0yDCQcA4R33"
subscribed_symbols = ["BTCUSDT", "ETHUSDT"]
subscribed_kline_intervals = ["1m", "1s"]
api_rate_limits = [[8, 1], [60000, 5000], [300000, 50000]]
stream_rate_limits = [[8, 1], [60000, 5000], [300000, 50000]]
stream_api_rate_limits = [[8, 1], [60000, 5000], [300000, 50000]]
kline_event_channel_capacity = 5000
trade_event_channel_capacity = 5000
depth_event_channel_capacity = 5000
ticker_event_channel_capacity = 5000
depth_cache_channel_capacity = 5000
order_event_channel_capacity = 5000
user_trade_event_channel_capacity = 5000
account_event_channel_capacity = 5000
stream_reconnect_interval_milli_secs = 3000
stream_api_reconnect_interval_milli_secs = 3000
api_timeout_milli_secs = 30000

[proxy]
url = "socks5://127.0.0.1:10808"
